# Hide splash message on bottom
splash = false

# preload = /usr/share/backgrounds/wallpaper.jpg
# wallpaper = ,/usr/share/backgrounds/wallpaper.jpg

preload = ~/Pictures/PixEz/126440227_p0.jpg
wallpaper = DP-1, ~/Pictures/PixEz/126440227_p0.jpg 

# Cirno
preload = /home/tiramisu/Pictures/Twitter/IMG_4732.JPG
wallpaper = DP-1, /home/tiramisu/Pictures/Twitter/IMG_4732.JPG

ipc = on

